<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EManagerPomoc</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
    <None Update="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>..\..\app_installed\Microsoft.Web.WebView2.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Wpf">
      <HintPath>..\..\app_installed\Microsoft.Web.WebView2.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="ScreenRecorderLib">
      <HintPath>..\..\app_installed\ScreenRecorderLib.dll</HintPath>
    </Reference>
    <Reference Include="Xabe.FFmpeg">
      <HintPath>..\..\app_installed\Xabe.FFmpeg.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis">
      <HintPath>..\..\app_installed\Google.Apis.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Auth">
      <HintPath>..\..\app_installed\Google.Apis.Auth.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Drive.v3">
      <HintPath>..\..\app_installed\Google.Apis.Drive.v3.dll</HintPath>
    </Reference>
    <Reference Include="Xabe.FFmpeg.Downloader">
      <HintPath>..\..\app_installed\Xabe.FFmpeg.Downloader.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Core">
      <HintPath>..\..\app_installed\Google.Apis.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>